name: example
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_mobx: ^1.0.1
  mobx_store_disposer:
    git: https://github.com/emanuel-braz/mobx_store_disposer.git

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.4
  mobx_codegen: ^1.0.2

flutter:
  uses-material-design: true